/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Enzo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        mbClientes = new javax.swing.JMenu();
        mbVeterinarios = new javax.swing.JMenu();
        mbProductos = new javax.swing.JMenu();
        miAlimento = new javax.swing.JMenuItem();
        miAccesorios = new javax.swing.JMenuItem();
        miMedicos = new javax.swing.JMenuItem();
        mbProveedores = new javax.swing.JMenu();
        miEmpresas = new javax.swing.JMenuItem();
        miFarmaceuticos = new javax.swing.JMenuItem();
        miAutonomos = new javax.swing.JMenuItem();
        mbTurnos = new javax.swing.JMenu();
        miCitas = new javax.swing.JMenuItem();
        miVisitas = new javax.swing.JMenuItem();
        miIntervenciones = new javax.swing.JMenuItem();
        mbArchivos = new javax.swing.JMenu();
        miABMClientes = new javax.swing.JMenuItem();
        miABMMascotas = new javax.swing.JMenuItem();
        miABMProductos = new javax.swing.JMenu();
        miABMAlimenticios = new javax.swing.JMenuItem();
        miABMAccesorios = new javax.swing.JMenuItem();
        miABMMedicos = new javax.swing.JMenuItem();
        miABMProveedores = new javax.swing.JMenu();
        miABMEmpresas = new javax.swing.JMenuItem();
        miABMFarmaceuticos = new javax.swing.JMenuItem();
        miABMAutonomos = new javax.swing.JMenuItem();
        miABMVeterinarios = new javax.swing.JMenuItem();
        mbHistoriales = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");

        jLabel1.setText("Veterinaria");

        mbClientes.setText("Clientes");
        jMenuBar2.add(mbClientes);

        mbVeterinarios.setText("Veterinarios");
        jMenuBar2.add(mbVeterinarios);

        mbProductos.setText("Productos");

        miAlimento.setText("Alimenticios");
        miAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAlimentoActionPerformed(evt);
            }
        });
        mbProductos.add(miAlimento);

        miAccesorios.setText("Accesorios");
        mbProductos.add(miAccesorios);

        miMedicos.setText("Medicos");
        mbProductos.add(miMedicos);

        jMenuBar2.add(mbProductos);

        mbProveedores.setText("Proveedores");

        miEmpresas.setText("Empresas");
        mbProveedores.add(miEmpresas);

        miFarmaceuticos.setText("Farmaceuticos");
        miFarmaceuticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFarmaceuticosActionPerformed(evt);
            }
        });
        mbProveedores.add(miFarmaceuticos);

        miAutonomos.setText("Autonomos");
        mbProveedores.add(miAutonomos);

        jMenuBar2.add(mbProveedores);

        mbTurnos.setText("Turnos");

        miCitas.setText("Citas");
        mbTurnos.add(miCitas);

        miVisitas.setText("Visitas");
        mbTurnos.add(miVisitas);

        miIntervenciones.setText("Intervenciones");
        mbTurnos.add(miIntervenciones);

        jMenuBar2.add(mbTurnos);

        mbArchivos.setText("Archivos");

        miABMClientes.setText("ABM Clientes");
        mbArchivos.add(miABMClientes);

        miABMMascotas.setText("ABM Mascotas");
        mbArchivos.add(miABMMascotas);

        miABMProductos.setText("ABM Productos");

        miABMAlimenticios.setText("Alimenticios");
        miABMProductos.add(miABMAlimenticios);

        miABMAccesorios.setText("Accesorios");
        miABMProductos.add(miABMAccesorios);

        miABMMedicos.setText("Medicos");
        miABMMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miABMMedicosActionPerformed(evt);
            }
        });
        miABMProductos.add(miABMMedicos);

        mbArchivos.add(miABMProductos);

        miABMProveedores.setText("ABM Proveedores");

        miABMEmpresas.setText("Empresas");
        miABMProveedores.add(miABMEmpresas);

        miABMFarmaceuticos.setText("Farmaceuticos");
        miABMProveedores.add(miABMFarmaceuticos);

        miABMAutonomos.setText("Autonomos");
        miABMProveedores.add(miABMAutonomos);

        mbArchivos.add(miABMProveedores);

        miABMVeterinarios.setText("ABM Veterinarios");
        miABMVeterinarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miABMVeterinariosActionPerformed(evt);
            }
        });
        mbArchivos.add(miABMVeterinarios);

        jMenuBar2.add(mbArchivos);

        mbHistoriales.setText("Historiales médicos");
        jMenuBar2.add(mbHistoriales);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel1)
                .addContainerGap(504, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addContainerGap(370, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAlimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAlimentoActionPerformed

    private void miFarmaceuticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFarmaceuticosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miFarmaceuticosActionPerformed

    private void miABMMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miABMMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miABMMedicosActionPerformed

    private void miABMVeterinariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miABMVeterinariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miABMVeterinariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu mbArchivos;
    private javax.swing.JMenu mbClientes;
    private javax.swing.JMenu mbHistoriales;
    private javax.swing.JMenu mbProductos;
    private javax.swing.JMenu mbProveedores;
    private javax.swing.JMenu mbTurnos;
    private javax.swing.JMenu mbVeterinarios;
    private javax.swing.JMenuItem miABMAccesorios;
    private javax.swing.JMenuItem miABMAlimenticios;
    private javax.swing.JMenuItem miABMAutonomos;
    private javax.swing.JMenuItem miABMClientes;
    private javax.swing.JMenuItem miABMEmpresas;
    private javax.swing.JMenuItem miABMFarmaceuticos;
    private javax.swing.JMenuItem miABMMascotas;
    private javax.swing.JMenuItem miABMMedicos;
    private javax.swing.JMenu miABMProductos;
    private javax.swing.JMenu miABMProveedores;
    private javax.swing.JMenuItem miABMVeterinarios;
    private javax.swing.JMenuItem miAccesorios;
    private javax.swing.JMenuItem miAlimento;
    private javax.swing.JMenuItem miAutonomos;
    private javax.swing.JMenuItem miCitas;
    private javax.swing.JMenuItem miEmpresas;
    private javax.swing.JMenuItem miFarmaceuticos;
    private javax.swing.JMenuItem miIntervenciones;
    private javax.swing.JMenuItem miMedicos;
    private javax.swing.JMenuItem miVisitas;
    // End of variables declaration//GEN-END:variables
}
